version: '3'
services:
  app:
    build: .
    container_name: tinytik-app # 为app服务指定容器名称
    ports:
      - "8081:8080" # 将容器端口 8080 映射到主机端口 8081
    depends_on:
      - mysql
      - redis
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=321+-321ToM
      - MYSQL_DB=tinytik
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  mysql:
    image: mysql:5.7
    container_name: tinytik-mysql # 为mysql服务指定容器名称
    environment:
      # - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=321+-321ToM
      - MYSQL_DATABASE=tinytik

  redis:
    image: redis:latest
    container_name: tinytik-redis # 为redis服务指定容器名称
