# server
server:
    port: 8080
    urlPre:  http://139.224.32.57:8080/
    #urlPre:  http://139.224.32.57:8081/

# mysql
datasource:
    username: root
    password: 321+-321ToM
    host: 127.0.0.1  
    port: 3306
    database: tinytik
    charset: utf8mb4
    parseTime: true
    loc: Asia/Shanghai

# # mysql
# datasource:
#     username: root
#     password: 321+-321ToM
#     host: tinytik-mysql  # MySQL 容器的 IP 地址
#     port: 3306  # MySQL 默认端口
#     database: tinytik
#     charset: utf8mb4
#     parseTime: true
#     loc: Asia/Shanghai


# email
email:
    alias:
    host: smtp.163.com
    port: 465
    username:
    password:

# redis
redis:
    address: 127.0.0.1
    port: 6379
    password:
    db: 0
    expire: 24h # s m h d

# #redis
# redis:
#     address: tinytik-redis
#     port: 6379
#     password:
#     db: 0
#     expire: 24h # s m h d
    

# logger
logger:
    path: logs
    name: TinyTik
    ext: log
    timeFormat: '2006-01-01'
